sudo: true
env:
  global:
    - CC_TEST_REPORTER_ID=690d2b62e0c4304ed271341a2ed1786a41629b5a50c4c4fc4be8fd3ee6a99f33
language: ruby
rvm:
  - 2.5.1
services:
  - docker
  - postgresql
addons:
  ssh_known_hosts:
    - 68.183.18.1
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database myapp_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
branches:
  only:
  - "/.*/"
script:
  - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
  - bundle install
  - bundle exec rake db:load_config
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake cucumber
  - bundle exec rspec
  - bundle exec rubocop
after_script:
  - ../cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  # Deploy develop on the staging environment
  - provider: script
    script: bash ../deploy/staging-deploy.sh
    skip_cleanup: true
    on:
      branch: develop
  # Deploy master on the production environment
  - provider: script
    script: bash ../deploy/production-deploy.sh
    skip_cleanup: true
    on:
      branch: master